### ISSUE TITLE
About unable to run cmg

### ISSUE THREAD

**Issue by sdu-ycy** [ikoutis/cmg-solver#1]
Hello, dear author, I still cannot run cmg after installation, the error message is shown below. Did I fail to install it correctly? Thanks for your answer.
Index exceeds array bounds.

Error in cmg_precondition>ldl_ (line 510)
    A = A(p,p);

Error in cmg_precondition (line 161)
        [L, D, p] = ldl_( A_(1:n-1,1:n-1) );

Error in cmg_sdd (line 12)
pfun = cmg_precondition(A);

Error in testcmg (line 7)
pfun = cmg_sdd(A);
 
![1](https://user-images.githubusercontent.com/69100026/94149697-cb7bb900-feaa-11ea-9c41-7c294c9a0100.png)
![2](https://user-images.githubusercontent.com/69100026/94149721-d1719a00-feaa-11ea-8063-fb74378f3cf7.png)

**Comment by ikoutis** [comment]
Hi, 

I most probably know what causes the issue, and I will fix it in the next few hours and post an update. But just in case, is it possible to share with me the specific matrix A that causes the problem?

**Comment by sdu-ycy** [comment]
Thank you for your reply. This is the program I run：
n = 5000;
A = eye(n) - 0.1*(diag(ones(n-1,1),1) + diag(ones(n-1,1),-1));
A = sparse(A);
b = randn(n,1);
tol = 1e-6;
iter = 50;
pfun = cmg_sdd(A);


[A.zip](https://github.com/ikoutis/cmg-solver/files/5277009/A.zip)

**Comment by ikoutis** [comment]
I just pushed an update. This now works on my side. Please check if it is OK, and let me know.

**Comment by sdu-ycy** [comment]
Thank you for your maintenance, but I still can't run it here. The error message is as follows:
Undefined function or variable 'mx_splitforest_'.

Undefined function or variable 'mx_splitforest_'.

Error in cmg_precondition>steiner_group (line 267)
        C = mx_splitforest_(uint32(C1-1))+1;    %+-1 c-indexing

Error in cmg_precondition (line 120)
        [cI, ~] = steiner_group(A_,dA_);

Error in cmg_sdd (line 12)
pfun = cmg_precondition(A);

Error in test (line 7)
pfun = cmg_sdd(A);

![1](https://user-images.githubusercontent.com/69100026/94211723-dbc08200-ff04-11ea-87de-1a152ba4716a.png)

**Comment by ikoutis** [comment]
That function must be under cmg\mex (after you compiled). The folder cmg\mex must be in your Matlab path.

**Comment by sdu-ycy** [comment]
Thank you for your reply, it can be used normally now. The first time I used the 'matlab' folder directly, an error message appeared. Later I used the 'cmg-matlab.zip' in the 'download' folder and it was able to run normally.

**Comment by ikoutis** [comment]
OK , apparently the source mx_splitforest_.c was missing. I fixed that too.

Thanks!
